"""
Report how much of a buoy's hourly record is interpolated rather than observed.

utils/data_processing.py reindexes every channel onto a full hourly grid and
fills missing hours by linear interpolation, so processed_data.pkl no longer
distinguishes observed from interpolated records. This script goes back to
the raw .txt files and reports: overall and per-split interpolated fraction,
gap-length distribution, the longest gaps, and — per (seq_len, lead_time)
combination in the Optuna search space — how many val/test samples have an
interpolated terminal-step target, any interpolated target step, or an
interpolated start token (last input hour, which is also the persistence
forecast).

The split is computed exactly as in nn/optimization.py::_prepare_dataloaders.
Output: results/data_gaps/gap_stats_{BUOY_ID}.md — the source for the gap
statistics quoted in manuscript/sections/02_methods.tex §Preprocessing.

Run manually:
    python scripts/gap_statistics.py
"""
import sys
import os

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))
from pathlib import Path

import numpy as np
import pandas as pd

from utils import read_txt, add_datetime_index

BUOY_ID = "32012"

# Must match the seq_len choices in nn/optimization.py::objective() and the
# lead times reported in the manuscript.
SEQ_LENS = [12, 24, 48, 96]
LEAD_TIMES = [12, 24, 48]

CHANNEL_FILES = ['density.txt', 'alpha1.txt', 'alpha2.txt', 'r1.txt', 'r2.txt']

project_root = Path(__file__).resolve().parent.parent
folder_path = project_root / "buoy_data" / BUOY_ID
out_path = project_root / "results" / "data_gaps" / f"gap_stats_{BUOY_ID}.md"


def observed_index(file_path):
    df = add_datetime_index(read_txt(file_path)).sort_index()
    return df.index[~df.index.duplicated()]


def gap_runs(missing, index):
    """(start, end, length_h) for each maximal run of missing hours."""
    runs, start = [], None
    for i, m in enumerate(missing):
        if m and start is None:
            start = i
        elif not m and start is not None:
            runs.append((index[start], index[i - 1], i - start))
            start = None
    if start is not None:
        runs.append((index[start], index[-1], len(missing) - start))
    return runs


def window_counts(m, seq_len, lead_time):
    """Sample counts touching interpolated hours, same windowing as prepare_y."""
    num_samples = len(m) - seq_len - lead_time + 1
    i = np.arange(num_samples)
    terminal = m[i + seq_len + lead_time - 1]
    any_target = np.array([m[k + seq_len:k + seq_len + lead_time].any() for k in i])
    start_token = m[i + seq_len - 1]
    return num_samples, terminal.sum(), any_target.sum(), start_token.sum()


indices = {f: observed_index(folder_path / f) for f in CHANNEL_FILES}
shared = all(idx.equals(indices['density.txt']) for idx in indices.values())
# Same grid as utils/data_processing.py: the span of the union of timestamps.
start = min(idx.min() for idx in indices.values())
end = max(idx.max() for idx in indices.values())
full_index = pd.date_range(start, end, freq='h')
# A record counts as interpolated if ANY channel is missing it.
missing = np.zeros(len(full_index), dtype=bool)
for idx in indices.values():
    missing |= ~full_index.isin(idx)

n = len(full_index)
train_end, val_end = int(0.7 * n), int(0.85 * n)
splits = {'train': slice(0, train_end), 'val': slice(train_end, val_end), 'test': slice(val_end, n)}

runs = gap_runs(missing, full_index)
lengths = np.array([r[2] for r in runs])

lines = [
    f"# Gap statistics — buoy {BUOY_ID}",
    "",
    f"Generated by `scripts/gap_statistics.py` from the raw `buoy_data/{BUOY_ID}/*.txt` files.",
    "",
    f"- All five spectral channels share identical timestamps: **{shared}**",
    f"- Hourly grid: {full_index[0]} to {full_index[-1]} ({n} records)",
    f"- Observed: {n - missing.sum()}; interpolated: **{missing.sum()} ({100 * missing.mean():.2f}%)**",
    f"- Gaps: {len(runs)}; longest: **{lengths.max()} h**; median: {np.median(lengths):.0f} h",
    "",
    "## Gap-length distribution",
    "",
    "| Length (h) | Count |",
    "|---|---|",
]
for length, count in zip(*np.unique(lengths, return_counts=True)):
    lines.append(f"| {length} | {count} |")

lines += ["", "## Gaps longer than 1 h", "", "| Start | End | Length (h) | Split |", "|---|---|---|---|"]
for start, end, length in sorted(runs, key=lambda r: -r[2]):
    if length <= 1:
        continue
    pos = full_index.get_loc(start)
    split = next(s for s, sl in splits.items() if sl.start <= pos < sl.stop)
    lines.append(f"| {start} | {end} | {length} | {split} |")

lines += ["", "## Per split", "", "| Split | Start | End | Records | Interpolated | % | Gaps | Longest (h) |",
          "|---|---|---|---|---|---|---|---|"]
for name, sl in splits.items():
    m = missing[sl]
    split_runs = [r for r in runs if full_index[sl][0] <= r[0] <= full_index[sl][-1]]
    longest = max((r[2] for r in split_runs), default=0)
    lines.append(f"| {name} | {full_index[sl][0]} | {full_index[sl][-1]} | {len(m)} | {m.sum()} | "
                 f"{100 * m.mean():.2f} | {len(split_runs)} | {longest} |")

for name in ('val', 'test'):
    m = missing[splits[name]]
    lines += ["", f"## {name} samples touching interpolated hours", "",
              "Terminal = forecast product (last target step); start token = last input hour "
              "(also the persistence forecast).", "",
              "| seq_len | lead (h) | Samples | Terminal interp. | % | Any target step interp. | % | Start token interp. |",
              "|---|---|---|---|---|---|---|---|"]
    for seq_len in SEQ_LENS:
        for lead_time in LEAD_TIMES:
            N, term, any_t, start_tok = window_counts(m, seq_len, lead_time)
            lines.append(f"| {seq_len} | {lead_time} | {N} | {term} | {100 * term / N:.2f} | "
                         f"{any_t} | {100 * any_t / N:.1f} | {start_tok} |")

out_path.parent.mkdir(parents=True, exist_ok=True)
out_path.write_text("\n".join(lines) + "\n")
print(f"Gap statistics written to {out_path}")
